version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crontab-ui
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - /etc/crontab:/etc/crontab
